export const KYB_PROVIDER = Symbol('KYB_PROVIDER');
export const SANCTIONS_PROVIDER = Symbol('SANCTIONS_PROVIDER');
export const WALLET_SCREENING_PROVIDER = Symbol('WALLET_SCREENING_PROVIDER');
export const VERIFICATION_SESSION_PROVIDER = Symbol('VERIFICATION_SESSION_PROVIDER');
